---
deployment:
    tasks:
        - export DEPLOYPATH=/home/ussander/developer.ussander.com/
        - /bin/cp -R upload/. $DEPLOYPATH
        - /bin/cp install.xml "$DEPLOYPATH"system/opencart-subcategory-image.ocmod.xml
